# data
train_src: "data/train.en"
train_trg: "data/train.vi"
valid_src: "data/tst2013.en"
valid_trg: "data/tst2013.vi"
test_src: "data/tst2012.en"
test_trg: "data/tst2012.vi"

# checkpoint
checkpoint_dir: "checkpoints"
checkpoint_best: "checkpoints/checkpoint_best.pt"
checkpoint_last: "checkpoints/checkpoint_last.pt"
checkpoint_results: "checkpoints/results.csv"
dataloaders: "checkpoints/dataloaders.pt"

# vocab
vocab_dir: "vocab"
vocab_en: "vocab/en_vocab.txt"
vocab_vi: "vocab/vi_vocab.txt"
    


# vocabulary options
min_freq: 1
vocab_size: null

# training hyperparameters
batch_size: 32
num_epochs: 20

# model architecture
d_model: 256
d_ff: 512
max_seq_len: 256
n_heads: 8
n_layers: 4
dropout: 0.1

# optimizer
init_lr: !!float 5e-4

# testing
beam_size: 1