# data
train_src: "dataset/train.en"
train_trg: "dataset/train.vi"
valid_src: "dataset/tst2013.en"
valid_trg: "dataset/tst2013.vi"
test_src: "dataset/tst2012.en"
test_trg: "dataset/tst2012.vi"

# checkpoint
checkpoint_dir: "checkpoints"
checkpoint_best: "checkpoint_best.pt"
checkpoint_last: "checkpoint_last.pt"
checkpoint_results: "results.csv"
dataloaders: "dataloaders.pt"

# vocab
vocab_dir: "vocab"
vocab_src: "src_vocab.txt"
vocab_trg: "trg_vocab.txt"
    
# vocabulary options
min_freq: 1
vocab_size: null

# training hyperparameters
batch_size: 32
num_epochs: 10

clip: 1.0

# model architecture
d_model: 256
d_ff: 512
max_seq_len: 256
n_heads: 8
n_layers: 3
dropout: 0.1

# optimizer
init_lr: !!float 5e-4

# testing
beam_size: 1